services:
  telemetry:
    enabled: true
    load_defaults: true
    config_file_env: "PERCONA_TEST_TELEMETRY_FILE"
    datasources:
      VM:
        enabled: true
        timeout: 2s
        address: http://localhost:9090/prometheus
      QANDB_SELECT:
        enabled: true
        timeout: 2s
        dsn: tcp://localhost:9000?database=pmm&block_size=10000&pool_size=2
      PMMDB_SELECT:
        enabled: true
        timeout: 10s
        use_separate_credentials: false
        separate_credentials:
          username: pmm
          password: pmm
    reporting:
      send_on_start: false
      send_on_start_env: "PERCONA_TEST_TELEMETRY_DISABLE_START_DELAY"
      interval: 24h
      interval_env: "PERCONA_TEST_TELEMETRY_INTERVAL"
      retry_backoff: 1h
      retry_backoff_env: "PERCONA_TEST_TELEMETRY_RETRY_BACKOFF"
      retry_count: 20
      send_timeout: 5s
